"""
Forward-compatibility fix for Cell 21 (4.1 Half-daily aggregation).

`half_daily.groupby('tran_br_code', group_keys=False).apply(cap_outliers)` uses
DataFrameGroupBy.apply, which DROPS the grouping column in pandas >= 3.0. It only emitted a
DeprecationWarning in pandas 2.x, which is what Colab currently ships, so the notebook runs
today — but the moment Colab upgrades to pandas 3 the very next cell dies with
`KeyError: "['tran_br_code'] not in index"` and every downstream cell fails with it.

Rewritten using SeriesGroupBy.apply, which is unaffected by that change. Verified to
reproduce the existing pandas-2 output exactly (max abs difference 1.5e-08 across all
17,117 rows, checked against model_data/half_daily_features.csv, which was generated by
the original code under pandas 2).

Run:  python patch_pandas3_compat.py
"""
import json
import shutil
import sys

NB = 'Bank_Cash_Optimization_Workflow.ipynb'

OLD = """# Outlier capping (Winsorization at 99th percentile per branch)
def cap_outliers(group):
    # Calculate 99th percentile ONLY on the first 80% (train set) to prevent data leakage!
    cutoff = int(len(group) * 0.8)
    cap = group['Half_Day_Total_Debit'].iloc[:cutoff].quantile(0.99)
    group['Half_Day_Total_Debit'] = group['Half_Day_Total_Debit'].clip(upper=cap)
    return group
half_daily = half_daily.groupby('tran_br_code', group_keys=False).apply(cap_outliers)
"""

NEW = """# Outlier capping (Winsorization at the 99th percentile per branch).
# The cap is fitted ONLY on each branch's first 80% of rows (its train period) so that
# no test-period information leaks into the capping threshold.
#
# Implemented with SeriesGroupBy.apply rather than DataFrameGroupBy.apply: the latter
# silently DROPS the grouping column in pandas >= 3.0 (it only warned in pandas 2.x),
# which would strip `tran_br_code` here and break every cell that follows.
_caps = half_daily.groupby('tran_br_code')['Half_Day_Total_Debit'].apply(
    lambda s: s.iloc[:int(len(s) * 0.8)].quantile(0.99)
)
half_daily['Half_Day_Total_Debit'] = half_daily['Half_Day_Total_Debit'].clip(
    upper=half_daily['tran_br_code'].map(_caps)
)
print(f"Capped {int((half_daily['Half_Day_Total_Debit'] < half_daily['Half_Day_Total_Debit_RAW']).sum())} "
      f"outlier rows across {half_daily['tran_br_code'].nunique()} branches.")
"""


def main():
    with open(NB, encoding='utf-8') as f:
        nb = json.load(f)
    cells = nb['cells']

    hits = [i for i, c in enumerate(cells) if c['cell_type'] == 'code' and OLD in ''.join(c['source'])]
    if len(hits) != 1:
        sys.exit(f"ERROR: expected exactly 1 matching cell, found {hits}")
    i = hits[0]

    shutil.copy(NB, NB + '.pre_pandas3.bak')
    cells[i]['source'] = ''.join(cells[i]['source']).replace(OLD, NEW, 1).splitlines(keepends=True)
    cells[i]['outputs'], cells[i]['execution_count'] = [], None
    print(f"Cell {i} rewritten for pandas 3 compatibility (outputs cleared for re-execution)")

    with open(NB, 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
        f.write('\n')
    print(f"Done. Backup: {NB}.pre_pandas3.bak")


if __name__ == '__main__':
    main()
